spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.43.212:3306/daoshicha_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root_pwd2021!
