server:
  port: 8080
  servlet:
    context-path: /daoshicha


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.43.212:3306/daoshicha?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: daoshicha
    password: daoshicha_test
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minidle: 5
    maxActive: 20
    maxWait: 60000
    filters: stat,wall,log4j

mybatis:
  mapper-locations: classpath:mappers/*/*.xml
